package example.kirana.models;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Document(collection = "transactions")
public class Transaction {

    @Id
    private String id;
    private String userId; // Foreign key reference to User
    private LocalDate transactionDate;
    private String currency;
    private BigDecimal originalAmount;
    private BigDecimal convertedAmount;
    private String type; // Credit or Debit
    // Add any other relevant fields

    // Constructors, getters, and setters are automatically generated by Lombok
}

