package example.kirana.models;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "users")
public class User {

    @Id
    private String id;
    private String name;
    private String username;
    private String password;
    private String role; // Roles: "ADMIN" or "EMPLOYEE"
    // Add any other relevant fields

    // Constructors, getters, and setters are automatically generated by Lombok
}

